version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  working_directory: ~/konfetti
  environment:
    _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "konfetti/build.gradle" }}-{{ checksum  "demo-google-play/build.gradle" }}-{{ checksum  "demo-simple-java/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Assemble demo-google-play apk
          command: ./gradlew :demo-google-play:assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "konfetti/build.gradle" }}-{{ checksum  "demo-google-play/build.gradle" }}-{{ checksum  "demo-simple-java/build.gradle" }}
      - store_artifacts:
          path: demo-google-play/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: demo-google-play/build/reports
          destination: reports
      - store_test_results:
          path: konfetti/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - build
            - app/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
